// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNPKJXQqaZcfP82AGOKYY5aTHHrIkPJ08',
    appId: '1:429873781095:web:253089685da70a6cc5f7c2',
    messagingSenderId: '429873781095',
    projectId: 'loginpage-77411',
    authDomain: 'loginpage-77411.firebaseapp.com',
    storageBucket: 'loginpage-77411.appspot.com',
    measurementId: 'G-RG43WBPT3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhmgV-GsdLSOM689UbdJyuRqVgu-Z07_Y',
    appId: '1:429873781095:android:e8d9f0648514af4ac5f7c2',
    messagingSenderId: '429873781095',
    projectId: 'loginpage-77411',
    storageBucket: 'loginpage-77411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB57WEKLgMquQbVbty51DZ9gzlC-aO_Q88',
    appId: '1:429873781095:ios:c2d7ffe2a9904634c5f7c2',
    messagingSenderId: '429873781095',
    projectId: 'loginpage-77411',
    storageBucket: 'loginpage-77411.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB57WEKLgMquQbVbty51DZ9gzlC-aO_Q88',
    appId: '1:429873781095:ios:6502576f9771cac3c5f7c2',
    messagingSenderId: '429873781095',
    projectId: 'loginpage-77411',
    storageBucket: 'loginpage-77411.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
